model_name: PE_Flow
exp_name: test

# general args
batch_size: 1
pretrain: pretrain/dsec.pth
evaluate: True

# data agrs
dataset: DSEC
data_root: /gdata2/lihl/dsec

npoint: 8192
nbin: 15
size: [480, 640]

# model args
train_iter: 4
eval_iter: 5